import { DashboardState } from "@/lib/types";

export const initialDashboardState: DashboardState = {
  projects: [
    {
      id: "p1",
      name: "Модернизация производственной линии",
      description:
        "Комплексная модернизация производственной линии с внедрением автоматизированных систем контроля качества.",
      status: "active",
      progress: 35,
      direction: "metallurgy",
      budget: { planned: 5000000, actual: 1800000, currency: "RUB" },
      dates: { start: "2026-01-15", end: "2026-12-31" },
      nextMilestone: { name: "Закупка оборудования", date: "2026-04-15" },
      team: ["Алексей М.", "Мария К.", "Дмитрий С."],
      risks: 3,
      location: "Екатеринбург",
      priority: "high",
      health: 74,
      objectives: [
        "Завершить проектную документацию.",
        "Заключить контракты с поставщиками.",
        "Провести монтаж и пусконаладку.",
      ],
      materials: 61,
      laborProductivity: 84,
      safety: { ltifr: 0.2, trir: 0.8 },
      history: [
        { date: "2026-01-22", progress: 8, budgetPlanned: 450000, budgetActual: 380000 },
        { date: "2026-02-05", progress: 14, budgetPlanned: 900000, budgetActual: 760000 },
        { date: "2026-02-19", progress: 21, budgetPlanned: 1350000, budgetActual: 1180000 },
        { date: "2026-03-05", progress: 29, budgetPlanned: 1750000, budgetActual: 1630000 },
        { date: "2026-03-19", progress: 35, budgetPlanned: 2200000, budgetActual: 1800000 },
      ],
    },
    {
      id: "p2",
      name: "Логистический хаб (Центральный регион)",
      description:
        "Создание регионального логистического центра для оптимизации доставки в центральную часть России.",
      status: "planning",
      progress: 15,
      direction: "logistics",
      budget: { planned: 3000000, actual: 450000, currency: "RUB" },
      dates: { start: "2026-02-01", end: "2026-10-31" },
      nextMilestone: { name: "Выбор площадки", date: "2026-05-01" },
      team: ["Алексей М.", "Елена В."],
      risks: 5,
      location: "Москва",
      priority: "critical",
      health: 58,
      objectives: [
        "Провести анализ локаций.",
        "Получить разрешительную документацию.",
        "Заключить договор аренды.",
      ],
      materials: 43,
      laborProductivity: 69,
      safety: { ltifr: 0.1, trir: 0.4 },
      history: [
        { date: "2026-02-01", progress: 2, budgetPlanned: 150000, budgetActual: 80000 },
        { date: "2026-02-12", progress: 5, budgetPlanned: 260000, budgetActual: 140000 },
        { date: "2026-02-26", progress: 8, budgetPlanned: 370000, budgetActual: 260000 },
        { date: "2026-03-10", progress: 12, budgetPlanned: 500000, budgetActual: 380000 },
        { date: "2026-03-24", progress: 15, budgetPlanned: 650000, budgetActual: 450000 },
      ],
    },
    {
      id: "p3",
      name: "Разработка мобильного приложения",
      description:
        "Создание кроссплатформенного мобильного приложения для клиентов компании.",
      status: "completed",
      progress: 100,
      direction: "trade",
      budget: { planned: 1500000, actual: 1400000, currency: "RUB" },
      dates: { start: "2025-11-01", end: "2025-12-31" },
      nextMilestone: null,
      team: ["Дмитрий С.", "Игорь П."],
      risks: 0,
      location: "Remote",
      priority: "medium",
      health: 92,
      objectives: [
        "Завершить разработку в срок.",
        "Пройти модерацию в сторах.",
      ],
      materials: 100,
      laborProductivity: 93,
      safety: { ltifr: 0, trir: 0.1 },
      history: [
        { date: "2025-11-01", progress: 0, budgetPlanned: 0, budgetActual: 0 },
        { date: "2025-11-15", progress: 25, budgetPlanned: 350000, budgetActual: 300000 },
        { date: "2025-12-01", progress: 60, budgetPlanned: 900000, budgetActual: 850000 },
        { date: "2025-12-15", progress: 90, budgetPlanned: 1300000, budgetActual: 1200000 },
        { date: "2025-12-31", progress: 100, budgetPlanned: 1500000, budgetActual: 1400000 },
      ],
    },
    {
      id: "p4",
      name: "Строительство складского комплекса",
      description:
        "Возведение складского комплекса класса А с автоматизированной системой хранения.",
      status: "active",
      progress: 62,
      direction: "construction",
      budget: { planned: 25000000, actual: 15500000, currency: "RUB" },
      dates: { start: "2025-06-01", end: "2026-06-30" },
      nextMilestone: { name: "Монтаж кровли", date: "2026-04-01" },
      team: ["Мария К.", "Елена В.", "Анна Л."],
      risks: 2,
      location: "Казань",
      priority: "high",
      health: 85,
      objectives: [
        "Завершить нулевой цикл.",
        "Возвести каркас здания.",
        "Установить складское оборудование.",
      ],
      materials: 78,
      laborProductivity: 88,
      safety: { ltifr: 0.3, trir: 1.2 },
      history: [
        { date: "2025-06-15", progress: 5, budgetPlanned: 1200000, budgetActual: 1150000 },
        { date: "2025-08-01", progress: 15, budgetPlanned: 3800000, budgetActual: 3600000 },
        { date: "2025-10-15", progress: 30, budgetPlanned: 7500000, budgetActual: 7200000 },
        { date: "2025-12-01", progress: 45, budgetPlanned: 11000000, budgetActual: 10500000 },
        { date: "2026-02-15", progress: 55, budgetPlanned: 13750000, budgetActual: 13500000 },
        { date: "2026-03-10", progress: 62, budgetPlanned: 15500000, budgetActual: 15500000 },
      ],
    },
    {
      id: "p5",
      name: "Внедрение CRM-системы",
      description:
        "Внедрение корпоративной CRM-системы с интеграцией в существующую IT-инфраструктуру.",
      status: "active",
      progress: 48,
      direction: "trade",
      budget: { planned: 800000, actual: 380000, currency: "RUB" },
      dates: { start: "2026-01-01", end: "2026-05-31" },
      nextMilestone: { name: "Импорт данных", date: "2026-03-20" },
      team: ["Игорь П.", "Дмитрий С."],
      risks: 4,
      location: "Remote",
      priority: "medium",
      health: 68,
      objectives: [
        "Настроить базовую функциональность.",
        "Перенести исторические данные.",
        "Обучить пользователей.",
      ],
      materials: 52,
      laborProductivity: 75,
      safety: { ltifr: 0, trir: 0 },
      history: [
        { date: "2026-01-15", progress: 10, budgetPlanned: 80000, budgetActual: 75000 },
        { date: "2026-02-01", progress: 25, budgetPlanned: 200000, budgetActual: 180000 },
        { date: "2026-02-15", progress: 35, budgetPlanned: 280000, budgetActual: 260000 },
        { date: "2026-03-01", progress: 42, budgetPlanned: 340000, budgetActual: 320000 },
        { date: "2026-03-10", progress: 48, budgetPlanned: 380000, budgetActual: 380000 },
      ],
    },
    {
      id: "p6",
      name: "Реконструкция офисного здания",
      description:
        "Капитальный ремонт и модернизация офисного здания с обновлением инженерных систем.",
      status: "at-risk",
      progress: 22,
      direction: "construction",
      budget: { planned: 12000000, actual: 4200000, currency: "RUB" },
      dates: { start: "2025-09-01", end: "2026-08-31" },
      nextMilestone: { name: "Замена оконных блоков", date: "2026-04-10" },
      team: ["Мария К.", "Анна Л."],
      risks: 7,
      location: "Новосибирск",
      priority: "critical",
      health: 42,
      objectives: [
        "Завершить демонтажные работы.",
        "Обновить электропроводку.",
        "Установить систему вентиляции.",
      ],
      materials: 35,
      laborProductivity: 58,
      safety: { ltifr: 0.5, trir: 1.8 },
      history: [
        { date: "2025-09-15", progress: 5, budgetPlanned: 600000, budgetActual: 700000 },
        { date: "2025-11-01", progress: 12, budgetPlanned: 1400000, budgetActual: 1800000 },
        { date: "2026-01-15", progress: 18, budgetPlanned: 2200000, budgetActual: 3000000 },
        { date: "2026-03-01", progress: 20, budgetPlanned: 2400000, budgetActual: 3800000 },
        { date: "2026-03-10", progress: 22, budgetPlanned: 2600000, budgetActual: 4200000 },
      ],
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "Подготовить ТЗ на оборудование",
      description: "Составить техническое задание для закупки производственного оборудования",
      status: "done",
      priority: "high",
      assignee: { id: "m1", name: "Алексей М.", initials: "АМ" },
      projectId: "p1",
      dueDate: "2026-02-28",
      createdAt: "2026-01-15",
      order: 0,
      tags: [],
    },
    {
      id: "t2",
      title: "Согласовать бюджет с финотделом",
      description: "Провести согласование бюджета проекта на 2026 год",
      status: "in-progress",
      priority: "critical",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p1",
      dueDate: "2026-03-15",
      createdAt: "2026-01-20",
      order: 0,
      tags: [],
    },
    {
      id: "t3",
      title: "Провести переговоры с поставщиками",
      description: "Сравнить предложения от 3+ поставщиков оборудования",
      status: "todo",
      priority: "high",
      assignee: { id: "m3", name: "Дмитрий С.", initials: "ДС" },
      projectId: "p1",
      dueDate: "2026-04-10",
      createdAt: "2026-02-01",
      order: 0,
      tags: [],
    },
    {
      id: "t4",
      title: "Анализ локаций для хаба",
      description: "Подготовить сравнительный анализ 5 потенциальных площадок",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m4", name: "Елена В.", initials: "ЕВ" },
      projectId: "p2",
      dueDate: "2026-03-20",
      createdAt: "2026-02-05",
      order: 0,
      tags: [],
    },
    {
      id: "t5",
      title: "Получить ТУ на подключение",
      description: "Оформить технические условия на электроснабжение",
      status: "todo",
      priority: "medium",
      assignee: { id: "m1", name: "Алексей М.", initials: "АМ" },
      projectId: "p2",
      dueDate: "2026-04-30",
      createdAt: "2026-02-10",
      order: 0,
      tags: [],
    },
    {
      id: "t6",
      title: "Монтаж опалубки (участок А)",
      description: "Установка опалубки для заливки фундамента на участке А",
      status: "done",
      priority: "high",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p4",
      dueDate: "2026-02-20",
      createdAt: "2026-02-01",
      order: 0,
      tags: [],
    },
    {
      id: "t7",
      title: "Контроль качества бетона",
      description: "Провести лабораторные испытания образцов бетона",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m6", name: "Анна Л.", initials: "АЛ" },
      projectId: "p4",
      dueDate: "2026-03-12",
      createdAt: "2026-03-01",
      order: 0,
      tags: [],
    },
    {
      id: "t8",
      title: "Настройка интеграции с 1С",
      description: "Настроить обмен данными между CRM и учётной системой",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m5", name: "Игорь П.", initials: "ИП" },
      projectId: "p5",
      dueDate: "2026-03-25",
      createdAt: "2026-02-15",
      order: 0,
      tags: [],
    },
    {
      id: "t9",
      title: "Обучение менеджеров",
      description: "Провести тренинг по работе в новой CRM-системе",
      status: "todo",
      priority: "medium",
      assignee: { id: "m3", name: "Дмитрий С.", initials: "ДС" },
      projectId: "p5",
      dueDate: "2026-04-15",
      createdAt: "2026-03-01",
      order: 0,
      tags: [],
    },
    {
      id: "t10",
      title: "Устранение протечек кровли",
      description: "Аварийные работы по устранению протечек на крыше здания",
      status: "in-progress",
      priority: "critical",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p6",
      dueDate: "2026-03-12",
      createdAt: "2026-03-08",
      order: 0,
      tags: [],
    },
    {
      id: "t11",
      title: "Согласование сметы",
      description: "Согласовать дополнительную смету на непредвиденные работы",
      status: "todo",
      priority: "critical",
      assignee: { id: "m6", name: "Анна Л.", initials: "АЛ" },
      projectId: "p6",
      dueDate: "2026-03-18",
      createdAt: "2026-03-05",
      order: 0,
      tags: [],
    },
  ],
  risks: [
    {
      id: "r1",
      projectId: "p1",
      title: "Задержка поставки оборудования",
      owner: "Дмитрий С.",
      probability: 0.5,
      impact: 0.7,
      status: "open",
      mitigation: "Резервный поставщик в регионе",
      category: "logistics",
    },
    {
      id: "r2",
      projectId: "p4",
      title: "Рост цен на стройматериалы",
      owner: "Мария К.",
      probability: 0.7,
      impact: 0.5,
      status: "open",
      mitigation: "Фиксация цен в договорах",
      category: "financial",
    },
    {
      id: "r3",
      projectId: "p4",
      title: "Нехватка квалифицированных кадров",
      owner: "Елена В.",
      probability: 0.5,
      impact: 0.7,
      status: "open",
      mitigation: "Привлечение подрядчиков",
      category: "resource",
    },
    {
      id: "r4",
      projectId: "p2",
      title: "Согласования в госорганах",
      owner: "Алексей М.",
      probability: 0.7,
      impact: 0.7,
      status: "open",
      mitigation: "Ранний старт процесса согласования",
      category: "administrative",
    },
    {
      id: "r5",
      projectId: "p6",
      title: "Превышение бюджета",
      owner: "Анна Л.",
      probability: 0.7,
      impact: 0.9,
      status: "open",
      mitigation: "Оптимизация затрат, пересмотр сметы",
      category: "financial",
    },
    {
      id: "r6",
      projectId: "p5",
      title: "Сбои при миграции данных",
      owner: "Игорь П.",
      probability: 0.3,
      impact: 0.7,
      status: "mitigated",
      mitigation: "Резервное копирование, поэтапный перенос",
      category: "technical",
    },
  ],
  team: [
    {
      id: "m1",
      name: "Алексей М.",
      role: "Руководитель проектов",
      email: "alexey.m@example.com",
      capacity: 100,
      allocated: 85,
      projects: ["p1", "p2"],
      location: "Москва",
    },
    {
      id: "m2",
      name: "Мария К.",
      role: "Руководитель строительства",
      email: "maria.k@example.com",
      capacity: 100,
      allocated: 95,
      projects: ["p1", "p4", "p6"],
      location: "Казань",
    },
    {
      id: "m3",
      name: "Дмитрий С.",
      role: "Менеджер по закупкам",
      email: "dmitry.s@example.com",
      capacity: 100,
      allocated: 70,
      projects: ["p1", "p5"],
      location: "Москва",
    },
    {
      id: "m4",
      name: "Елена В.",
      role: "Бизнес-аналитик",
      email: "elena.v@example.com",
      capacity: 100,
      allocated: 60,
      projects: ["p2", "p4"],
      location: "Москва",
    },
    {
      id: "m5",
      name: "Игорь П.",
      role: "IT-специалист",
      email: "igor.p@example.com",
      capacity: 100,
      allocated: 80,
      projects: ["p3", "p5"],
      location: "Remote",
    },
    {
      id: "m6",
      name: "Анна Л.",
      role: "Финансовый контролёр",
      email: "anna.l@example.com",
      capacity: 100,
      allocated: 75,
      projects: ["p4", "p6"],
      location: "Новосибирск",
    },
  ],
  documents: [],
  milestones: [],
  auditLogEntries: [],
  currentUser: {
    id: "u1",
    name: "Александр Гребешок",
    role: "PM",
    email: "admin@example.com",
  },
};

export function getMockProjects() {
  return initialDashboardState.projects;
}

export function getMockTasks() {
  return initialDashboardState.tasks;
}

export function getMockTeam() {
  return initialDashboardState.team;
}

export function getMockRisks() {
  return initialDashboardState.risks;
}


