import { DashboardState } from "@/lib/types";
import { getTodayIsoDate } from "@/lib/date";

const mockAssignees: Record<string, { id: string; name: string; initials: string }> = {
  "Алексей М.": { id: "m1", name: "Алексей М.", initials: "АМ" },
  "Мария К.": { id: "m2", name: "Мария К.", initials: "МК" },
  "Дмитрий С.": { id: "m3", name: "Дмитрий С.", initials: "ДС" },
  "Елена В.": { id: "m4", name: "Елена В.", initials: "ЕВ" },
  "Игорь П.": { id: "m5", name: "Игорь П.", initials: "ИП" },
  "Анна Л.": { id: "m6", name: "Анна Л.", initials: "АЛ" },
};

export const initialDashboardState: DashboardState = {
  projects: [
    {
      id: "p1",
      name: "Модернизация производственной линии",
      description:
        "Комплексная модернизация производственной линии с внедрением автоматизированных систем контроля качества.",
      status: "active",
      progress: 35,
      direction: "metallurgy",
      budget: { planned: 5000000, actual: 1800000, currency: "RUB" },
      dates: { start: "2026-01-15", end: "2026-12-31" },
      nextMilestone: { name: "Закупка оборудования", date: "2026-04-15" },
      team: ["Алексей М.", "Мария К.", "Дмитрий С."],
      risks: 3,
      location: "Екатеринбург",
      priority: "high",
      health: 74,
      objectives: [
        "Завершить проектную документацию.",
        "Заключить контракты с поставщиками.",
        "Провести монтаж и пусконаладку.",
      ],
      materials: 61,
      laborProductivity: 84,
      safety: { ltifr: 0.2, trir: 0.8 },
      history: [
        { date: "2026-01-22", progress: 8, budgetPlanned: 450000, budgetActual: 380000 },
        { date: "2026-02-05", progress: 14, budgetPlanned: 900000, budgetActual: 760000 },
        { date: "2026-02-19", progress: 21, budgetPlanned: 1350000, budgetActual: 1180000 },
        { date: "2026-03-05", progress: 29, budgetPlanned: 1750000, budgetActual: 1630000 },
        { date: "2026-03-19", progress: 35, budgetPlanned: 2200000, budgetActual: 1800000 },
      ],
    },
    {
      id: "p2",
      name: "Логистический хаб (Центральный регион)",
      description:
        "Создание регионального логистического центра для оптимизации доставки в центральную часть России.",
      status: "planning",
      progress: 15,
      direction: "logistics",
      budget: { planned: 3000000, actual: 450000, currency: "RUB" },
      dates: { start: "2026-02-01", end: "2026-10-31" },
      nextMilestone: { name: "Выбор площадки", date: "2026-05-01" },
      team: ["Алексей М.", "Елена В."],
      risks: 5,
      location: "Москва",
      priority: "critical",
      health: 58,
      objectives: [
        "Провести анализ локаций.",
        "Получить разрешительную документацию.",
        "Заключить договор аренды.",
      ],
      materials: 43,
      laborProductivity: 69,
      safety: { ltifr: 0.1, trir: 0.4 },
      history: [
        { date: "2026-02-01", progress: 2, budgetPlanned: 150000, budgetActual: 80000 },
        { date: "2026-02-12", progress: 5, budgetPlanned: 260000, budgetActual: 140000 },
        { date: "2026-02-26", progress: 8, budgetPlanned: 370000, budgetActual: 260000 },
        { date: "2026-03-10", progress: 12, budgetPlanned: 500000, budgetActual: 380000 },
        { date: "2026-03-24", progress: 15, budgetPlanned: 650000, budgetActual: 450000 },
      ],
    },
    {
      id: "p3",
      name: "Разработка мобильного приложения",
      description:
        "Создание кроссплатформенного мобильного приложения для клиентов компании.",
      status: "completed",
      progress: 100,
      direction: "it",
      budget: { planned: 1500000, actual: 1400000, currency: "RUB" },
      dates: { start: "2025-11-01", end: "2025-12-31" },
      nextMilestone: null,
      team: ["Дмитрий С.", "Игорь П."],
      risks: 0,
      location: "Remote",
      priority: "medium",
      health: 92,
      objectives: [
        "Завершить разработку в срок.",
        "Пройти модерацию в сторах.",
      ],
      materials: 100,
      laborProductivity: 93,
      safety: { ltifr: 0, trir: 0.1 },
      history: [
        { date: "2025-11-01", progress: 0, budgetPlanned: 0, budgetActual: 0 },
        { date: "2025-11-15", progress: 25, budgetPlanned: 350000, budgetActual: 300000 },
        { date: "2025-12-01", progress: 60, budgetPlanned: 900000, budgetActual: 850000 },
        { date: "2025-12-15", progress: 90, budgetPlanned: 1300000, budgetActual: 1200000 },
        { date: "2025-12-31", progress: 100, budgetPlanned: 1500000, budgetActual: 1400000 },
      ],
    },
    {
      id: "p4",
      name: "Строительство складского комплекса",
      description:
        "Возведение складского комплекса класса А с автоматизированной системой хранения.",
      status: "active",
      progress: 62,
      direction: "construction",
      budget: { planned: 25000000, actual: 15500000, currency: "RUB" },
      dates: { start: "2025-06-01", end: "2026-06-30" },
      nextMilestone: { name: "Монтаж кровли", date: "2026-04-01" },
      team: ["Мария К.", "Елена В.", "Анна Л."],
      risks: 2,
      location: "Казань",
      priority: "high",
      health: 85,
      objectives: [
        "Завершить нулевой цикл.",
        "Возвести каркас здания.",
        "Установить складское оборудование.",
      ],
      materials: 78,
      laborProductivity: 88,
      safety: { ltifr: 0.3, trir: 1.2 },
      history: [
        { date: "2025-06-15", progress: 5, budgetPlanned: 1200000, budgetActual: 1150000 },
        { date: "2025-08-01", progress: 15, budgetPlanned: 3800000, budgetActual: 3600000 },
        { date: "2025-10-15", progress: 30, budgetPlanned: 7500000, budgetActual: 7200000 },
        { date: "2025-12-01", progress: 45, budgetPlanned: 11000000, budgetActual: 10500000 },
        { date: "2026-02-15", progress: 55, budgetPlanned: 13750000, budgetActual: 13500000 },
        { date: "2026-03-10", progress: 62, budgetPlanned: 15500000, budgetActual: 15500000 },
      ],
    },
    {
      id: "p5",
      name: "Внедрение CRM-системы",
      description:
        "Внедрение корпоративной CRM-системы с интеграцией в существующую IT-инфраструктуру.",
      status: "active",
      progress: 48,
      direction: "it",
      budget: { planned: 800000, actual: 380000, currency: "RUB" },
      dates: { start: "2026-01-01", end: "2026-05-31" },
      nextMilestone: { name: "Импорт данных", date: "2026-03-20" },
      team: ["Игорь П.", "Дмитрий С."],
      risks: 4,
      location: "Remote",
      priority: "medium",
      health: 68,
      objectives: [
        "Настроить базовую функциональность.",
        "Перенести исторические данные.",
        "Обучить пользователей.",
      ],
      materials: 52,
      laborProductivity: 75,
      safety: { ltifr: 0, trir: 0 },
      history: [
        { date: "2026-01-15", progress: 10, budgetPlanned: 80000, budgetActual: 75000 },
        { date: "2026-02-01", progress: 25, budgetPlanned: 200000, budgetActual: 180000 },
        { date: "2026-02-15", progress: 35, budgetPlanned: 280000, budgetActual: 260000 },
        { date: "2026-03-01", progress: 42, budgetPlanned: 340000, budgetActual: 320000 },
        { date: "2026-03-10", progress: 48, budgetPlanned: 380000, budgetActual: 380000 },
      ],
    },
    {
      id: "p6",
      name: "Реконструкция офисного здания",
      description:
        "Капитальный ремонт и модернизация офисного здания с обновлением инженерных систем.",
      status: "at-risk",
      progress: 22,
      direction: "construction",
      budget: { planned: 12000000, actual: 4200000, currency: "RUB" },
      dates: { start: "2025-09-01", end: "2026-08-31" },
      nextMilestone: { name: "Замена оконных блоков", date: "2026-04-10" },
      team: ["Мария К.", "Анна Л."],
      risks: 7,
      location: "Новосибирск",
      priority: "critical",
      health: 42,
      objectives: [
        "Завершить демонтажные работы.",
        "Обновить электропроводку.",
        "Установить систему вентиляции.",
      ],
      materials: 35,
      laborProductivity: 58,
      safety: { ltifr: 0.5, trir: 1.8 },
      history: [
        { date: "2025-09-15", progress: 5, budgetPlanned: 600000, budgetActual: 700000 },
        { date: "2025-11-01", progress: 12, budgetPlanned: 1400000, budgetActual: 1800000 },
        { date: "2026-01-15", progress: 18, budgetPlanned: 2200000, budgetActual: 3000000 },
        { date: "2026-03-01", progress: 20, budgetPlanned: 2400000, budgetActual: 3800000 },
        { date: "2026-03-10", progress: 22, budgetPlanned: 2600000, budgetActual: 4200000 },
      ],
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "Подготовить ТЗ на оборудование",
      description: "Составить техническое задание для закупки производственного оборудования",
      status: "done",
      priority: "high",
      assignee: { id: "m1", name: "Алексей М.", initials: "АМ" },
      projectId: "p1",
      dueDate: "2026-02-28",
      labels: ["закупки", "документация"],
      createdAt: "2026-01-15",
      updatedAt: "2026-02-25",
    },
    {
      id: "t2",
      title: "Согласовать бюджет с финотделом",
      description: "Провести согласование бюджета проекта на 2026 год",
      status: "in-progress",
      priority: "critical",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p1",
      dueDate: "2026-03-15",
      labels: ["финансы"],
      createdAt: "2026-01-20",
      updatedAt: "2026-03-10",
    },
    {
      id: "t3",
      title: "Провести переговоры с поставщиками",
      description: "Сравнить предложения от 3+ поставщиков оборудования",
      status: "todo",
      priority: "high",
      assignee: { id: "m3", name: "Дмитрий С.", initials: "ДС" },
      projectId: "p1",
      dueDate: "2026-04-10",
      labels: ["закупки"],
      createdAt: "2026-02-01",
      updatedAt: "2026-02-01",
    },
    {
      id: "t4",
      title: "Анализ локаций для хаба",
      description: "Подготовить сравнительный анализ 5 потенциальных площадок",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m4", name: "Елена В.", initials: "ЕВ" },
      projectId: "p2",
      dueDate: "2026-03-20",
      labels: ["аналитика"],
      createdAt: "2026-02-05",
      updatedAt: "2026-03-08",
    },
    {
      id: "t5",
      title: "Получить ТУ на подключение",
      description: "Оформить технические условия на электроснабжение",
      status: "todo",
      priority: "medium",
      assignee: { id: "m1", name: "Алексей М.", initials: "АМ" },
      projectId: "p2",
      dueDate: "2026-04-30",
      labels: ["документация"],
      createdAt: "2026-02-10",
      updatedAt: "2026-02-10",
    },
    {
      id: "t6",
      title: "Монтаж опалубки (участок А)",
      description: "Установка опалубки для заливки фундамента на участке А",
      status: "done",
      priority: "high",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p4",
      dueDate: "2026-02-20",
      labels: ["строительство"],
      createdAt: "2026-02-01",
      updatedAt: "2026-02-18",
    },
    {
      id: "t7",
      title: "Контроль качества бетона",
      description: "Провести лабораторные испытания образцов бетона",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m6", name: "Анна Л.", initials: "АЛ" },
      projectId: "p4",
      dueDate: "2026-03-12",
      labels: ["контроль качества"],
      createdAt: "2026-03-01",
      updatedAt: "2026-03-10",
    },
    {
      id: "t8",
      title: "Настройка интеграции с 1С",
      description: "Настроить обмен данными между CRM и учётной системой",
      status: "in-progress",
      priority: "high",
      assignee: { id: "m5", name: "Игорь П.", initials: "ИП" },
      projectId: "p5",
      dueDate: "2026-03-25",
      labels: ["интеграция", "IT"],
      createdAt: "2026-02-15",
      updatedAt: "2026-03-10",
    },
    {
      id: "t9",
      title: "Обучение менеджеров",
      description: "Провести тренинг по работе в новой CRM-системе",
      status: "todo",
      priority: "medium",
      assignee: { id: "m3", name: "Дмитрий С.", initials: "ДС" },
      projectId: "p5",
      dueDate: "2026-04-15",
      labels: ["обучение"],
      createdAt: "2026-03-01",
      updatedAt: "2026-03-01",
    },
    {
      id: "t10",
      title: "Устранение протечек кровли",
      description: "Аварийные работы по устранению протечек на крыше здания",
      status: "in-progress",
      priority: "critical",
      assignee: { id: "m2", name: "Мария К.", initials: "МК" },
      projectId: "p6",
      dueDate: "2026-03-12",
      labels: ["аварийные работы"],
      createdAt: "2026-03-08",
      updatedAt: "2026-03-10",
    },
    {
      id: "t11",
      title: "Согласование сметы",
      description: "Согласовать дополнительную смету на непредвиденные работы",
      status: "todo",
      priority: "critical",
      assignee: { id: "m6", name: "Анна Л.", initials: "АЛ" },
      projectId: "p6",
      dueDate: "2026-03-18",
      labels: ["финансы", "документация"],
      createdAt: "2026-03-05",
      updatedAt: "2026-03-05",
    },
  ],
  risks: [
    {
      id: "r1",
      title: "Задержка поставки оборудования",
      description: "Риск срыва сроков поставки из-за логистических проблем",
      probability: "medium",
      impact: "high",
      projectId: "p1",
      status: "active",
      mitigation: "Резервный поставщик в регионе",
      owner: "Дмитрий С.",
      createdAt: "2026-01-20",
    },
    {
      id: "r2",
      title: "Рост цен на стройматериалы",
      description: "Волатильность цен на строительные материалы",
      probability: "high",
      impact: "medium",
      projectId: "p4",
      status: "active",
      mitigation: "Фиксация цен в договорах",
      owner: "Мария К.",
      createdAt: "2026-01-15",
    },
    {
      id: "r3",
      title: "Нехватка квалифицированных кадров",
      description: "Дефицит специалистов для монтажных работ",
      probability: "medium",
      impact: "high",
      projectId: "p4",
      status: "active",
      mitigation: "Привлечение подрядчиков",
      owner: "Елена В.",
      createdAt: "2026-02-01",
    },
    {
      id: "r4",
      title: "Согласования в госорганах",
      description: "Длительные сроки получения разрешительной документации",
      probability: "high",
      impact: "high",
      projectId: "p2",
      status: "active",
      mitigation: "Ранний старт процесса согласования",
      owner: "Алексей М.",
      createdAt: "2026-02-05",
    },
    {
      id: "r5",
      title: "Превышение бюджета",
      description: "Риск значительного превышения запланированного бюджета",
      probability: "high",
      impact: "critical",
      projectId: "p6",
      status: "active",
      mitigation: "Оптимизация затрат, пересмотр сметы",
      owner: "Анна Л.",
      createdAt: "2026-01-10",
    },
    {
      id: "r6",
      title: "Сбои при миграции данных",
      description: "Потеря данных при переносе из старых систем",
      probability: "low",
      impact: "high",
      projectId: "p5",
      status: "mitigated",
      mitigation: "Резервное копирование, поэтапный перенос",
      owner: "Игорь П.",
      createdAt: "2026-01-25",
    },
  ],
  team: [
    {
      id: "m1",
      name: "Алексей М.",
      role: "Руководитель проектов",
      email: "alexey.m@example.com",
      initials: "АМ",
      capacity: 100,
      currentLoad: 85,
      skills: ["Управление проектами", "Переговоры", "Финансы"],
    },
    {
      id: "m2",
      name: "Мария К.",
      role: "Руководитель строительства",
      email: "maria.k@example.com",
      initials: "МК",
      capacity: 100,
      currentLoad: 95,
      skills: ["Строительство", "Контроль качества", "Технадзор"],
    },
    {
      id: "m3",
      name: "Дмитрий С.",
      role: "Менеджер по закупкам",
      email: "dmitry.s@example.com",
      initials: "ДС",
      capacity: 100,
      currentLoad: 70,
      skills: ["Закупки", "Логистика", "Аналитика"],
    },
    {
      id: "m4",
      name: "Елена В.",
      role: "Бизнес-аналитик",
      email: "elena.v@example.com",
      initials: "ЕВ",
      capacity: 100,
      currentLoad: 60,
      skills: ["Анализ данных", "Документация", "Исследования"],
    },
    {
      id: "m5",
      name: "Игорь П.",
      role: "IT-специалист",
      email: "igor.p@example.com",
      initials: "ИП",
      capacity: 100,
      currentLoad: 80,
      skills: ["Интеграции", "Разработка", "Базы данных"],
    },
    {
      id: "m6",
      name: "Анна Л.",
      role: "Финансовый контролёр",
      email: "anna.l@example.com",
      initials: "АЛ",
      capacity: 100,
      currentLoad: 75,
      skills: ["Финансы", "Бюджетирование", "Отчётность"],
    },
  ],
  notifications: [
    {
      id: "n1",
      type: "warning",
      title: "Приближается дедлайн",
      message: 'Задача "Согласовать бюджет" должна быть выполнена через 5 дней',
      timestamp: new Date().toISOString(),
      read: false,
      projectId: "p1",
    },
    {
      id: "n2",
      type: "info",
      title: "Новый комментарий",
      message: "Мария К. добавила комментарий к задаче",
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      read: false,
      projectId: "p4",
    },
    {
      id: "n3",
      type: "success",
      title: "Задача завершена",
      message: 'Дмитрий С. выполнил задачу "Подготовить ТЗ"',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      read: true,
      projectId: "p1",
    },
    {
      id: "n4",
      type: "error",
      title: "Критический риск",
      message: 'Проект "Реконструкция офиса" превысил бюджет на 61%',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      read: false,
      projectId: "p6",
    },
  ],
  analytics: {
    totalProjects: 6,
    activeProjects: 4,
    completedProjects: 1,
    atRiskProjects: 1,
    totalTasks: 11,
    completedTasks: 2,
    overdueTasks: 1,
    totalBudget: { planned: 47300000, actual: 22730000, currency: "RUB" },
    budgetUtilization: 48,
    averageHealth: 69.8,
    topRisks: [
      { projectId: "p6", riskCount: 7, severity: "critical" },
      { projectId: "p2", riskCount: 5, severity: "high" },
    ],
  },
};

export function getMockProjects() {
  return initialDashboardState.projects;
}

export function getMockTasks() {
  return initialDashboardState.tasks;
}

export function getMockTeam() {
  return initialDashboardState.team;
}

export function getMockRisks() {
  return initialDashboardState.risks;
}

export function getMockAnalytics() {
  return initialDashboardState.analytics;
}

export function getMockNotifications() {
  return initialDashboardState.notifications;
}
