import { DashboardState } from "@/lib/types";
import { getTodayIsoDate } from "@/lib/date";

export const initialDashboardState: DashboardState = {
  projects: [
    {
      id: "p1",
      name: "ЧЭМК — переработка дунита",
      description:
        "Запуск цепочки переработки дунита в огнеупорные материалы с площадкой в Харпе и контуром коммерциализации через индустриальных партнёров.",
      status: "active",
      progress: 35,
      direction: "metallurgy",
      budget: { planned: 5000000, actual: 1800000, currency: "RUB" },
      dates: { start: "2026-01-15", end: "2026-12-31" },
      nextMilestone: { name: "КП для МИПТЭК", date: "2026-04-15" },
      team: ["Саша", "Иван Аксарин", "Михаил Петров"],
      risks: 3,
      location: "Харп, ЯНАО",
      priority: "high",
      health: 74,
      objectives: [
        "Собрать коммерческую модель переработки.",
        "Подписать рамочные условия с индустриальным заказчиком.",
        "Подтвердить supply chain по сырью и логистике.",
      ],
      materials: 61,
      laborProductivity: 84,
      safety: { ltifr: 0.2, trir: 0.8 },
      history: [
        { date: "2026-01-22", progress: 8, budgetPlanned: 450000, budgetActual: 380000 },
        { date: "2026-02-05", progress: 14, budgetPlanned: 900000, budgetActual: 760000 },
        { date: "2026-02-19", progress: 21, budgetPlanned: 1350000, budgetActual: 1180000 },
        { date: "2026-03-05", progress: 29, budgetPlanned: 1750000, budgetActual: 1630000 },
        { date: "2026-03-19", progress: 35, budgetPlanned: 2200000, budgetActual: 1800000 },
      ],
    },
    {
      id: "p2",
      name: "Бентонитовые глины (KZ → RF)",
      description:
        "Поиск карьеров, оценка качества сырья и настройка импортного маршрута из Казахстана на Челябинский металлургический кластер.",
      status: "planning",
      progress: 15,
      direction: "logistics",
      budget: { planned: 3000000, actual: 450000, currency: "RUB" },
      dates: { start: "2026-02-01", end: "2026-10-31" },
      nextMilestone: { name: "Найти карьер в KZ", date: "2026-05-01" },
      team: ["Саша", "Екатерина Белая"],
      risks: 5,
      location: "Казахстан → Челябинск",
      priority: "critical",
      health: 58,
      objectives: [
        "Сформировать shortlist поставщиков.",
        "Подтвердить качество материала по лабораторным анализам.",
        "Просчитать валютные и логистические риски.",
      ],
      materials: 43,
      laborProductivity: 69,
      safety: { ltifr: 0.1, trir: 0.4 },
      history: [
        { date: "2026-02-01", progress: 2, budgetPlanned: 150000, budgetActual: 80000 },
        { date: "2026-02-12", progress: 5, budgetPlanned: 260000, budgetActual: 140000 },
        { date: "2026-02-26", progress: 8, budgetPlanned: 370000, budgetActual: 260000 },
        { date: "2026-03-10", progress: 12, budgetPlanned: 500000, budgetActual: 380000 },
        { date: "2026-03-24", progress: 15, budgetPlanned: 650000, budgetActual: 450000 },
      ],
    },
    {
      id: "p3",
      name: "Ёлки — поставка к Новому году",
      description:
        "Сезонный трейдинговый проект по закупке и поставке ёлок с фокусом на прогнозируемый спрос и минимизацию складских остатков.",
      status: "completed",
      progress: 100,
      direction: "trade",
      budget: { planned: 1500000, actual: 1400000, currency: "RUB" },
      dates: { start: "2025-11-01", end: "2025-12-31" },
      nextMilestone: null,
      team: ["Саша", "Партнёр"],
      risks: 0,
      location: "Сургут",
      priority: "medium",
      health: 92,
      objectives: [
        "Закрыть сезон без остатков.",
        "Удержать валовую маржу в целевом диапазоне.",
      ],
      materials: 100,
      laborProductivity: 93,
      safety: { ltifr: 0, trir: 0.1 },
      history: [
        { date: "2025-11-07", progress: 12, budgetPlanned: 250000, budgetActual: 220000 },
        { date: "2025-11-21", progress: 34, budgetPlanned: 600000, budgetActual: 510000 },
        { date: "2025-12-05", progress: 68, budgetPlanned: 980000, budgetActual: 920000 },
        { date: "2025-12-19", progress: 91, budgetPlanned: 1280000, budgetActual: 1250000 },
        { date: "2025-12-31", progress: 100, budgetPlanned: 1500000, budgetActual: 1400000 },
      ],
    },
    {
      id: "p4",
      name: "Северная логистика — зимник и перевалка",
      description:
        "Подготовка временной инфраструктуры и логистического окна для поставок строительных материалов на северные объекты.",
      status: "at-risk",
      progress: 48,
      direction: "construction",
      budget: { planned: 7800000, actual: 4550000, currency: "RUB" },
      dates: { start: "2025-12-10", end: "2026-08-20" },
      nextMilestone: { name: "Окно зимника", date: "2026-03-18" },
      team: ["Саша", "Павел Орлов", "Ирина Лапина"],
      risks: 6,
      location: "ЯНАО",
      priority: "critical",
      health: 46,
      objectives: [
        "Удержать график завоза по сезонному окну.",
        "Не допустить кассового разрыва на подрядчиках.",
        "Синхронизировать поставки и технику на площадке.",
      ],
      materials: 57,
      laborProductivity: 63,
      safety: { ltifr: 0.6, trir: 1.4 },
      history: [
        { date: "2025-12-24", progress: 10, budgetPlanned: 700000, budgetActual: 720000 },
        { date: "2026-01-14", progress: 24, budgetPlanned: 1600000, budgetActual: 1820000 },
        { date: "2026-02-04", progress: 31, budgetPlanned: 2450000, budgetActual: 2810000 },
        { date: "2026-02-25", progress: 42, budgetPlanned: 3350000, budgetActual: 3880000 },
        { date: "2026-03-18", progress: 48, budgetPlanned: 4300000, budgetActual: 4550000 },
      ],
    },
  ],
  tasks: [
    {
      id: "t1",
      projectId: "p2",
      title: "Найти карьер бентонита в Казахстане",
      description: "Исследовать 2-3 карьера и запросить коммерческие предложения.",
      status: "in-progress",
      order: 0,
      assignee: "Саша",
      dueDate: "2026-03-15",
      priority: "high",
      tags: ["research", "procurement"],
      createdAt: getTodayIsoDate(),
    },
    {
      id: "t2",
      projectId: "p1",
      title: "Подготовить КП для ЧЭМК",
      description: "Собрать коммерческое предложение по дуниту.",
      status: "todo",
      order: 0,
      assignee: "Иван Аксарин",
      dueDate: "2026-03-20",
      priority: "medium",
      tags: ["sales", "documentation"],
      createdAt: "2026-03-05",
    },
    {
      id: "t3",
      projectId: "p1",
      title: "Согласовать СП с ЧЭМК",
      description: "Финализировать юридическую структуру совместного предприятия.",
      status: "blocked",
      order: 0,
      assignee: "Саша",
      dueDate: "2026-04-01",
      priority: "high",
      tags: ["legal", "partnership"],
      blockedReason: "Ждём решения от ЧЭМК",
      createdAt: "2026-02-20",
    },
    {
      id: "t4",
      projectId: "p4",
      title: "Подтвердить слот на зимник",
      description: "Синхронизировать окно прохода с подрядчиками и перевозчиком.",
      status: "in-progress",
      order: 0,
      assignee: "Павел Орлов",
      dueDate: "2026-03-09",
      priority: "critical",
      tags: ["logistics", "timeline"],
      createdAt: "2026-02-28",
    },
    {
      id: "t5",
      projectId: "p4",
      title: "Проверить кассовый разрыв по субподрядчикам",
      description: "Собрать прогноз платежей на ближайшие 6 недель.",
      status: "todo",
      order: 0,
      assignee: "Ирина Лапина",
      dueDate: "2026-03-12",
      priority: "high",
      tags: ["finance"],
      createdAt: "2026-03-01",
    },
    {
      id: "t6",
      projectId: "p3",
      title: "Закрыть итоговый сезонный отчёт",
      description: "Фиксация финансового и операционного результата.",
      status: "done",
      order: 0,
      assignee: "Саша",
      dueDate: "2026-01-10",
      priority: "low",
      tags: ["reporting"],
      createdAt: "2025-12-31",
    },
    {
      id: "t7",
      projectId: "p1",
      title: "Подготовить safety briefing для площадки",
      description: "Обновить вводный пакет по технике безопасности.",
      status: "done",
      order: 0,
      assignee: "Михаил Петров",
      dueDate: "2026-02-14",
      priority: "medium",
      tags: ["safety"],
      createdAt: "2026-01-29",
    },
  ],
  team: [
    {
      id: "m1",
      name: "Саша",
      role: "Руководитель проектов",
      email: "agrebeshok@mail.ru",
      capacity: 100,
      allocated: 85,
      projects: ["ЧЭМК", "Бентонит", "Ёлки", "Северная логистика"],
      location: "Екатеринбург",
    },
    {
      id: "m2",
      name: "Иван Аксарин",
      role: "Партнёр",
      email: "ivan@example.com",
      capacity: 50,
      allocated: 30,
      projects: ["ЧЭМК"],
      location: "Челябинск",
    },
    {
      id: "m3",
      name: "Михаил Петров",
      role: "Операционный директор",
      email: "mp@example.com",
      capacity: 80,
      allocated: 62,
      projects: ["ЧЭМК", "Северная логистика"],
      location: "Тюмень",
    },
    {
      id: "m4",
      name: "Екатерина Белая",
      role: "Закупки и логистика",
      email: "ek@example.com",
      capacity: 100,
      allocated: 76,
      projects: ["Бентонит", "Северная логистика"],
      location: "Астана",
    },
    {
      id: "m5",
      name: "Павел Орлов",
      role: "Руководитель площадки",
      email: "po@example.com",
      capacity: 100,
      allocated: 91,
      projects: ["Северная логистика"],
      location: "Салехард",
    },
    {
      id: "m6",
      name: "Ирина Лапина",
      role: "Финансовый контроль",
      email: "il@example.com",
      capacity: 70,
      allocated: 54,
      projects: ["Северная логистика", "ЧЭМК"],
      location: "Москва",
    },
  ],
  risks: [
    {
      id: "r1",
      projectId: "p1",
      title: "Задержка согласования модели СП",
      owner: "Саша",
      probability: 3,
      impact: 5,
      status: "open",
      mitigation: "Готовим альтернативный сценарий поставки без СП.",
      category: "legal",
    },
    {
      id: "r2",
      projectId: "p2",
      title: "Низкое качество образцов бентонита",
      owner: "Екатерина Белая",
      probability: 4,
      impact: 4,
      status: "open",
      mitigation: "Добавить вторую лабораторию и резервных поставщиков.",
      category: "quality",
    },
    {
      id: "r3",
      projectId: "p2",
      title: "Курсовая волатильность по контракту",
      owner: "Ирина Лапина",
      probability: 3,
      impact: 4,
      status: "mitigated",
      mitigation: "Закладываем валютный коридор и опционы в калькуляцию.",
      category: "finance",
    },
    {
      id: "r4",
      projectId: "p4",
      title: "Погодное окно может закрыться раньше плана",
      owner: "Павел Орлов",
      probability: 5,
      impact: 5,
      status: "open",
      mitigation: "Переносим критичные объёмы на ближайшие 10 дней.",
      category: "timeline",
    },
    {
      id: "r5",
      projectId: "p4",
      title: "Нехватка оборотного капитала на субподряд",
      owner: "Ирина Лапина",
      probability: 4,
      impact: 5,
      status: "open",
      mitigation: "Ежедневный cash board и переговоры по отсрочке.",
      category: "finance",
    },
    {
      id: "r6",
      projectId: "p1",
      title: "Срыв графика по технологическим тестам",
      owner: "Михаил Петров",
      probability: 2,
      impact: 4,
      status: "closed",
      mitigation: "Закрыто после подтверждения нового графика.",
      category: "operations",
    },
  ],
  documents: [
    {
      id: "d1",
      projectId: "p1",
      title: "Технико-экономическое обоснование",
      type: "PDF",
      owner: "Саша",
      updatedAt: "2026-03-04",
      size: "4.2 MB",
    },
    {
      id: "d2",
      projectId: "p1",
      title: "Коммерческое предложение v3",
      type: "DOCX",
      owner: "Иван Аксарин",
      updatedAt: "2026-03-06",
      size: "1.1 MB",
    },
    {
      id: "d3",
      projectId: "p2",
      title: "Матрица поставщиков KZ",
      type: "XLSX",
      owner: "Екатерина Белая",
      updatedAt: "2026-03-05",
      size: "820 KB",
    },
    {
      id: "d4",
      projectId: "p4",
      title: "План зимника и перевалки",
      type: "PDF",
      owner: "Павел Орлов",
      updatedAt: getTodayIsoDate(),
      size: "6.8 MB",
    },
  ],
  milestones: [
    {
      id: "mstone1",
      projectId: "p1",
      name: "KPI board",
      start: "2026-01-15",
      end: "2026-02-05",
      status: "completed",
      progress: 100,
    },
    {
      id: "mstone2",
      projectId: "p1",
      name: "КП для МИПТЭК",
      start: "2026-03-10",
      end: "2026-04-15",
      status: "active",
      progress: 64,
    },
    {
      id: "mstone3",
      projectId: "p2",
      name: "Shortlist карьеров",
      start: "2026-02-08",
      end: "2026-05-01",
      status: "planning",
      progress: 26,
    },
    {
      id: "mstone4",
      projectId: "p4",
      name: "Окно зимника",
      start: "2026-02-20",
      end: "2026-03-18",
      status: "at-risk",
      progress: 48,
    },
    {
      id: "mstone5",
      projectId: "p4",
      name: "Пик перевалки",
      start: "2026-03-18",
      end: "2026-05-12",
      status: "planning",
      progress: 18,
    },
  ],
  currentUser: {
    id: "user1",
    name: "Саша",
    role: "PM",
    email: "sasha@example.com",
  },
  auditLogEntries: [
    {
      id: "log1",
      projectId: "p1",
      action: "created",
      userId: "user1",
      userName: "Саша",
      timestamp: "2026-03-09T10:00:00Z",
      details: "Проект создан",
    },
    {
      id: "log2",
      projectId: "p1",
      action: "status_changed",
      userId: "user1",
      userName: "Саша",
      timestamp: "2026-03-09T11:30:00Z",
      details: "Статус изменён на active",
    },
    {
      id: "log3",
      projectId: "p1",
      action: "milestone_reached",
      userId: "user1",
      userName: "Саша",
      timestamp: "2026-03-09T12:00:00Z",
      details: "Милestone достигнут: КП для МИПТЭК",
    },
    {
      id: "log4",
      projectId: "p2",
      action: "updated",
      userId: "user1",
      userName: "Саша",
      timestamp: "2026-03-09T09:00:00Z",
      details: "Бюджет обновлён",
    },
    {
      id: "log5",
      projectId: "p2",
      action: "created",
      userId: "user1",
      userName: "Саша",
      timestamp: "2026-03-08T14:00:00Z",
      details: "Проект создан",
    },
  ],
};
