"use client";

import { Download, FileSpreadsheet, FileText } from "lucide-react";

import { Button } from "@/components/ui/button";
import { useDashboard } from "@/components/dashboard-provider";
import { useLocale } from "@/contexts/locale-context";
import { jsPDF } from "jspdf";
import { toast } from "sonner";

interface DashboardExportProps {
  className?: string;
}

export function DashboardExport({ className }: DashboardExportProps) {
  const { projects, tasks, risks, team } = useDashboard();
  const { t, formatDateLocalized } = useLocale();

  const exportToPDF = async () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("CEOClaw Dashboard Summary", pageWidth / 2, y, { align: "center" });
      y += 10;

      // Date
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated: ${formatDateLocalized(new Date().toISOString(), "d MMM yyyy HH:mm")}`, pageWidth / 2, y, { align: "center" });
      y += 20;

      // Projects Section
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Projects Overview", 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const activeProjects = projects.filter(p => p.status !== "completed");
      const completedProjects = projects.filter(p => p.status === "completed");
      
      doc.text(`Total Projects: ${projects.length}`, 20, y);
      y += 6;
      doc.text(`Active: ${activeProjects.length} | Completed: ${completedProjects.length}`, 20, y);
      y += 10;

      // Top 5 Projects
      activeProjects.slice(0, 5).forEach((project, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(`${index + 1}. ${project.name} - ${project.progress}% (${project.status})`, 25, y);
        y += 6;
      });
      y += 10;

      // Tasks Section
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Tasks Summary", 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const todoTasks = tasks.filter(t => t.status === "todo");
      const inProgressTasks = tasks.filter(t => t.status === "in-progress");
      const doneTasks = tasks.filter(t => t.status === "done");
      const blockedTasks = tasks.filter(t => t.status === "blocked");

      doc.text(`Total Tasks: ${tasks.length}`, 20, y);
      y += 6;
      doc.text(`To Do: ${todoTasks.length} | In Progress: ${inProgressTasks.length} | Done: ${doneTasks.length} | Blocked: ${blockedTasks.length}`, 20, y);
      y += 10;

      // Risks Section
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Risks Overview", 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const openRisks = risks.filter(r => r.status === "open");
      const criticalRisks = risks.filter(r => r.probability >= 5 || r.impact >= 5);

      doc.text(`Total Risks: ${risks.length}`, 20, y);
      y += 6;
      doc.text(`Open: ${openRisks.length} | Critical: ${criticalRisks.length}`, 20, y);
      y += 10;

      // Team Section
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Team", 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Team Members: ${team.length}`, 20, y);
      y += 10;

      // Footer
      doc.setFontSize(8);
      doc.text("Generated by CEOClaw - AI-powered Project Management Dashboard", pageWidth / 2, 285, { align: "center" });

      // Save
      const filename = `ceoclaw-dashboard-${new Date().toISOString().split("T")[0]}.pdf`;
      doc.save(filename);
      
      toast.success(t("export.pdfSuccess") || "PDF exported successfully");
    } catch (error) {
      console.error("[DashboardExport] PDF export error:", error);
      toast.error(t("export.pdfError") || "Failed to export PDF");
    }
  };

  const exportToCSV = async () => {
    try {
      // Projects CSV
      const projectsCSV = [
        ["Name", "Status", "Progress", "Priority", "Start Date", "End Date", "Budget Planned", "Budget Actual"],
        ...projects.map(p => [
          p.name,
          p.status,
          `${p.progress}%`,
          p.priority,
          p.dates.start,
          p.dates.end,
          `${p.budget.planned} ${p.budget.currency}`,
          `${p.budget.actual} ${p.budget.currency}`,
        ]),
      ].map(row => row.join(",")).join("\n");

      // Tasks CSV
      const tasksCSV = [
        ["Title", "Status", "Priority", "Due Date", "Assignee", "Project"],
        ...tasks.map(t => [
          `"${t.title}"`,
          t.status,
          t.priority,
          t.dueDate,
          t.assignee?.name || "",
          projects.find(p => p.id === t.projectId)?.name || "",
        ]),
      ].map(row => row.join(",")).join("\n");

      // Download projects
      const projectsBlob = new Blob([projectsCSV], { type: "text/csv;charset=utf-8;" });
      const projectsUrl = URL.createObjectURL(projectsBlob);
      const projectsLink = document.createElement("a");
      projectsLink.href = projectsUrl;
      projectsLink.download = `ceoclaw-projects-${new Date().toISOString().split("T")[0]}.csv`;
      projectsLink.click();
      URL.revokeObjectURL(projectsUrl);

      // Download tasks
      const tasksBlob = new Blob([tasksCSV], { type: "text/csv;charset=utf-8;" });
      const tasksUrl = URL.createObjectURL(tasksBlob);
      const tasksLink = document.createElement("a");
      tasksLink.href = tasksUrl;
      tasksLink.download = `ceoclaw-tasks-${new Date().toISOString().split("T")[0]}.csv`;
      tasksLink.click();
      URL.revokeObjectURL(tasksUrl);

      toast.success(t("export.csvSuccess") || "CSV files exported successfully");
    } catch (error) {
      console.error("[DashboardExport] CSV export error:", error);
      toast.error(t("export.csvError") || "Failed to export CSV");
    }
  };

  return (
    <div className={`flex gap-2 ${className || ""}`}>
      <Button
        onClick={exportToPDF}
        size="sm"
        variant="secondary"
      >
        <FileText className="mr-2 h-4 w-4" />
        PDF
      </Button>
      <Button
        onClick={exportToCSV}
        size="sm"
        variant="secondary"
      >
        <FileSpreadsheet className="mr-2 h-4 w-4" />
        CSV
      </Button>
    </div>
  );
}
